### ISSUE TITLE
small bug in code in docs on ci.inria.fr site

### ISSUE THREAD

**Issue by fuhrmanator** [svenvc/docs#9]
Thanks for NeoCSV! It's super useful (I'm using it on 1G csv files now...)

I was looking at https://ci.inria.fr/pharo-contribution/job/EnterprisePharoBook/lastSuccessfulBuild/artifact/book-result/NeoCSV/NeoCSV.html which seems to have more info than the readme here. I wasn't sure which one is (supposed to be) more recent, but Google tends to find the ci.inria.fr one when a search for NeoCSV is done.

Anyway, I think I found a mistake in the selective read example in 4.3:

```smalltalk
Array streamContents: [ :out |
  'paul.csv' asFileReference readStreamDo: [ :input |
      (NeoCSVReader on: (ZnBufferedReadStream on: in))
         skipHeader;
         addIntegerField;
         addSymbolField;
         addIntegerField;
         addFieldConverter: [ :x | x = #true ];
         do: [ :each |
            each third < 1000
               ifTrue: [ out nextPut: each ] ] ] ].
```

The third line should have

```smalltalk
(ZnBufferedReadStream on: input)
```

**Comment by svenvc** [comment]
Yes, that is correct, well spotted. Thx

https://github.com/SquareBracketAssociates/EnterprisePharo/commit/9571dce3fccb865cbced586f226ffff276029202
